sudo: required
servies :
 - docker

before_install:
 - docker build -t govindashrit/docker-react -f Dockerfile.dev .

script :
 - docker run -e CI=true govindashrit/docker-react npm run test -- --coverage